// Code generated by lab.nexedi.com/kirr/go123/tracing/cmd/gotrace; DO NOT EDIT.

package tracetest_test
// code generated for tracepoints

import (
	"lab.nexedi.com/kirr/go123/tracing"
	"unsafe"
)

// traceevent: traceHello(who string)

type _t_traceHello struct {
	tracing.Probe
	probefunc     func(who string)
}

var _traceHello *_t_traceHello

func traceHello(who string) {
	if _traceHello != nil {
		_traceHello_run(who)
	}
}

func _traceHello_run(who string) {
	for p := _traceHello; p != nil; p = (*_t_traceHello)(unsafe.Pointer(p.Next())) {
		p.probefunc(who)
	}
}

func traceHello_Attach(pg *tracing.ProbeGroup, probe func(who string)) *tracing.Probe {
	p := _t_traceHello{probefunc: probe}
	tracing.AttachProbe(pg, (**tracing.Probe)(unsafe.Pointer(&_traceHello)), &p.Probe)
	return &p.Probe
}

// traceevent: traceHi(who string)

type _t_traceHi struct {
	tracing.Probe
	probefunc     func(who string)
}

var _traceHi *_t_traceHi

func traceHi(who string) {
	if _traceHi != nil {
		_traceHi_run(who)
	}
}

func _traceHi_run(who string) {
	for p := _traceHi; p != nil; p = (*_t_traceHi)(unsafe.Pointer(p.Next())) {
		p.probefunc(who)
	}
}

func traceHi_Attach(pg *tracing.ProbeGroup, probe func(who string)) *tracing.Probe {
	p := _t_traceHi{probefunc: probe}
	tracing.AttachProbe(pg, (**tracing.Probe)(unsafe.Pointer(&_traceHi)), &p.Probe)
	return &p.Probe
}

// trace export signature
func _trace_exporthash_2cac17aa362e1c23f638766808e976bffdb10ba8() {}
